name: MageEnv        # or tutor-ai-l, whichever you chose
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10      # pin a compatible Python
  - manim            # gets installed by Conda
  - pip              # so we can pull pure‐Python libs

  - pip:
    - python-dotenv
    - openai
    - elevenlabs
