name: tutor-ai-l
channels:
  - conda-forge
dependencies:
  - python=3.11          # or whatever minor version you prefer
  - manim                # the Manim library itself
  - texlive-core         # a minimal TeX Live distribution
  - dvisvgm              # DVI → SVG converter used by Manim
  - dvipng               # (optional) DVI → PNG converter
  - pip                   # so you can still pip-install anything else
  - pip:
      - your-other-pip-deps  # if you have extra pip packages, list them here
